title: Within — Eileen Coutras
description: Values-driven systems + data storytelling
theme: jekyll-theme-cayman

# Optional links (show up in the header/footer)
social_links:
  linkedin: https://www.linkedin.com/in/eileen-coutras-387b592b/
  github: https://github.com/EileenCoutras
  email: mailto:ecoutras@gmail.com
